services:
  postgres:
    image: postgres
    env_file:
      - "../.env"
    container_name: postgres-go-chat
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: