services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - "./.env"
    container_name: postgres-go-chat
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - go_chat_app:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - "./.env"
    container_name: pgadmin-go-chat
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - ${PG_ADMIN_PORT}:80
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge

volumes:
  go_chat_app:
